import type { BeautyEdit, Outfit } from "./types";

export const catalog: Outfit[] = [
  {
    id: "navy-tailoring",
    title: "Navy Tailoring",
    description: "A confident, structured full-look for polished first impressions.",
    occasions: ["interview", "date"],
    styles: ["classic"],
    formality: "polished",
    budget: "mid",
    garmentCategory: "full_body",
    assetPath: "/catalog/navy-tailoring.svg",
    beautyTags: ["hydration", "texture"],
  },
  {
    id: "ivory-jumpsuit",
    title: "Ivory Jumpsuit",
    description: "A clean, composed silhouette with a minimal finish.",
    occasions: ["interview", "wedding", "reset"],
    styles: ["minimal"],
    formality: "polished",
    budget: "mid",
    garmentCategory: "full_body",
    assetPath: "/catalog/ivory-jumpsuit.svg",
    beautyTags: ["hydration"],
  },
  {
    id: "plum-wrap-dress",
    title: "Plum Wrap Dress",
    description: "A vivid, expressive choice for a dressier occasion.",
    occasions: ["date", "wedding"],
    styles: ["bold"],
    formality: "formal",
    budget: "premium",
    garmentCategory: "full_body",
    assetPath: "/catalog/plum-wrap-dress.svg",
    beautyTags: ["radiance"],
  },
  {
    id: "graphite-set",
    title: "Graphite Set",
    description: "A formal, refined set that keeps the focus on the moment.",
    occasions: ["interview"],
    styles: ["classic"],
    formality: "formal",
    budget: "premium",
    garmentCategory: "full_body",
    assetPath: "/catalog/graphite-set.svg",
    beautyTags: ["texture"],
  },
  {
    id: "sage-midi",
    title: "Sage Midi",
    description: "A softly tailored midi look for effortless polish.",
    occasions: ["date", "wedding"],
    styles: ["minimal"],
    formality: "polished",
    budget: "mid",
    garmentCategory: "full_body",
    assetPath: "/catalog/sage-midi.svg",
    beautyTags: ["hydration", "radiance"],
  },
  {
    id: "cocoa-blazer-set",
    title: "Cocoa Blazer Set",
    description: "A warm, approachable tailored option with a relaxed edge.",
    occasions: ["interview", "reset"],
    styles: ["classic"],
    formality: "polished",
    budget: "value",
    garmentCategory: "full_body",
    assetPath: "/catalog/cocoa-blazer-set.svg",
    beautyTags: ["hydration"],
  },
  {
    id: "blue-satin-set",
    title: "Blue Satin Set",
    description: "A luminous statement set for a memorable celebration.",
    occasions: ["wedding", "date"],
    styles: ["bold"],
    formality: "formal",
    budget: "premium",
    garmentCategory: "full_body",
    assetPath: "/catalog/blue-satin-set.svg",
    beautyTags: ["radiance"],
  },
  {
    id: "linen-layered-look",
    title: "Linen Layered Look",
    description: "An easy, breathable full look for a low-pressure reset.",
    occasions: ["reset", "wedding"],
    styles: ["minimal"],
    formality: "relaxed",
    budget: "value",
    garmentCategory: "full_body",
    assetPath: "/catalog/linen-layered-look.svg",
    beautyTags: ["hydration"],
  },
  {
    id: "black-evening-look",
    title: "Black Evening Look",
    description: "A crisp, elevated look for a confident night out.",
    occasions: ["date", "wedding"],
    styles: ["bold"],
    formality: "formal",
    budget: "premium",
    garmentCategory: "full_body",
    assetPath: "/catalog/black-evening-look.svg",
    beautyTags: ["texture", "radiance"],
  },
];

export const beautyEdits: BeautyEdit[] = [
  { id: "hydration-edit", title: "Comfort-first prep", description: "A simple moisture-focused edit for a fresh-feeling finish.", tags: ["hydration"] },
  { id: "texture-edit", title: "Smooth base edit", description: "A lightweight cosmetic edit for a soft, even-looking base.", tags: ["texture"] },
  { id: "radiance-edit", title: "Soft-radiance edit", description: "A subtle glow-focused edit for your chosen occasion.", tags: ["radiance"] },
  { id: "everyday-edit", title: "Everyday prep", description: "A simple, optional beauty edit built around your routine.", tags: ["everyday"] },
  { id: "calm-edit", title: "Minimal routine edit", description: "A low-step beauty edit that keeps the focus on your look.", tags: ["minimal"] },
  { id: "signature-edit", title: "Signature finish", description: "A flexible finishing edit for the look you selected.", tags: ["signature"] },
];
